version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: benyo2
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3001:3000"
    depends_on:
      - mysql
    networks:
      - mynetwork
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: benyo2
      DB_NAME: els
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mynetwork

volumes:
  mysql-data:

networks:
  mynetwork:
    driver: bridge
