const exercises = [
  { name: "Fekvenyomás", bodyPart: "chest", category: "barbell" },
  { name: "Guggolás", bodyPart: "legs", category: "barbell" },
  { name: "Felhúzás", bodyPart: "back", category: "barbell" },
  { name: "Vállból nyomás", bodyPart: "shoulders", category: "barbell" },
  { name: "Evezés", bodyPart: "back", category: "barbell" },
  { name: "Bicepsz", bodyPart: "arms", category: "dumbell" },
  { name: "Tricepsz letolás", bodyPart: "arms", category: "dumbell" },
  { name: "Oldalemelés", bodyPart: "shoulders", category: "dumbell" },
  { name: "Fekvenyomás", bodyPart: "chest", category: "dumbell" },
  { name: "Felhúzás", bodyPart: "back", category: "dumbell" },
  { name: "Húzódzkodás", bodyPart: "back", category: "bodyweight" },
  { name: "Fekvőtámasz", bodyPart: "chest", category: "bodyweight" },
  { name: "Plank", bodyPart: "core", category: "duration" },
  { name: "Felülés", bodyPart: "core", category: "bodyweight" },
  { name: "Kitörés", bodyPart: "legs", category: "bodyweight" },
  { name: "Burpee", bodyPart: "full body", category: "bodyweight" },
  { name: "Dobozra ugrás", bodyPart: "legs", category: "bodyweight" },
  { name: "Ugrókötél", bodyPart: "legs", category: "duration" },
  { name: "Futás", bodyPart: "legs", category: "distance" },
  { name: "Kerékpározás", bodyPart: "legs", category: "cardio" },
  { name: "Evezőgép", bodyPart: "full body", category: "distance" },
  { name: "Úszás", bodyPart: "full body", category: "distance" },
  { name: "Elliptikus tréner", bodyPart: "other", category: "duration" },
  { name: "Séta", bodyPart: "legs", category: "duration" },
  { name: "Lépcső gép", bodyPart: "legs", category: "duration" },
  { name: "Russian Twist", bodyPart: "core", category: "bodyweight" },
  { name: "Lógó lábemelés", bodyPart: "core", category: "bodyweight" },
  { name: "Tolódzkodás", bodyPart: "chest", category: "bodyweight" },
  { name: "Farmer séta", bodyPart: "full body", category: "dumbell" },
  { name: "Szán tolás", bodyPart: "full body", category: "other" },
  { name: "Kötélcsapkodás", bodyPart: "full body", category: "cardio" },
  { name: "Oldalsó plank", bodyPart: "core", category: "duration" },
  { name: "Homorítás", bodyPart: "core", category: "machine" },
  {
    name: "Tárogatás",
    bodyPart: "chest",
    category: "cable",
  },
  { name: "Face pulls", bodyPart: "shoulders", category: "cable" },
  { name: "Lábemelés", bodyPart: "core", category: "bodyweight" },
  { name: "Kalapács bicepsz", bodyPart: "arms", category: "dumbell" },
];

const food = [
  {
    name: "Alma",
    caloriesPer100g: 52,
    proteinPer100g: 0.3,
    carbsPer100g: 14,
    fatsPer100g: 0.2,
  },
  {
    name: "Banán",
    caloriesPer100g: 89,
    proteinPer100g: 1.1,
    carbsPer100g: 22.8,
    fatsPer100g: 0.3,
  },
  {
    name: "Körte",
    caloriesPer100g: 57,
    proteinPer100g: 0.4,
    carbsPer100g: 15,
    fatsPer100g: 0.2,
  },
  {
    name: "Szilva",
    caloriesPer100g: 46,
    proteinPer100g: 0.7,
    carbsPer100g: 11.4,
    fatsPer100g: 0.3,
  },
  {
    name: "Őszibarack",
    caloriesPer100g: 39,
    proteinPer100g: 0.9,
    carbsPer100g: 9.6,
    fatsPer100g: 0.2,
  },
  {
    name: "Narancs",
    caloriesPer100g: 47,
    proteinPer100g: 0.9,
    carbsPer100g: 11.8,
    fatsPer100g: 0.1,
  },
  {
    name: "Szőlő",
    caloriesPer100g: 69,
    proteinPer100g: 0.7,
    carbsPer100g: 18.1,
    fatsPer100g: 0.2,
  },
  {
    name: "Eper",
    caloriesPer100g: 32,
    proteinPer100g: 0.8,
    carbsPer100g: 7.7,
    fatsPer100g: 0.3,
  },
  {
    name: "Málna",
    caloriesPer100g: 52,
    proteinPer100g: 1.5,
    carbsPer100g: 11.9,
    fatsPer100g: 0.7,
  },
  {
    name: "Áfonya",
    caloriesPer100g: 57,
    proteinPer100g: 0.7,
    carbsPer100g: 14.5,
    fatsPer100g: 0.3,
  },
  {
    name: "Avokádó",
    caloriesPer100g: 160,
    proteinPer100g: 2,
    carbsPer100g: 8.5,
    fatsPer100g: 14.7,
  },
  {
    name: "Paradicsom",
    caloriesPer100g: 18,
    proteinPer100g: 0.9,
    carbsPer100g: 3.9,
    fatsPer100g: 0.2,
  },
  {
    name: "Uborka",
    caloriesPer100g: 16,
    proteinPer100g: 0.7,
    carbsPer100g: 3.6,
    fatsPer100g: 0.1,
  },
  {
    name: "Zöldpaprika",
    caloriesPer100g: 20,
    proteinPer100g: 1,
    carbsPer100g: 4.7,
    fatsPer100g: 0.2,
  },
  {
    name: "Brokkoli",
    caloriesPer100g: 34,
    proteinPer100g: 2.8,
    carbsPer100g: 6.6,
    fatsPer100g: 0.4,
  },
  {
    name: "Karfiol",
    caloriesPer100g: 25,
    proteinPer100g: 1.9,
    carbsPer100g: 4.9,
    fatsPer100g: 0.3,
  },
  {
    name: "Cékla",
    caloriesPer100g: 43,
    proteinPer100g: 1.6,
    carbsPer100g: 9.6,
    fatsPer100g: 0.2,
  },
  {
    name: "Káposzta",
    caloriesPer100g: 25,
    proteinPer100g: 1.3,
    carbsPer100g: 5.8,
    fatsPer100g: 0.1,
  },
  {
    name: "Sárgarépa",
    caloriesPer100g: 41,
    proteinPer100g: 0.9,
    carbsPer100g: 9.6,
    fatsPer100g: 0.2,
  },
  {
    name: "Zöldborsó",
    caloriesPer100g: 81,
    proteinPer100g: 5.4,
    carbsPer100g: 14.5,
    fatsPer100g: 0.4,
  },
  {
    name: "Hagyma",
    caloriesPer100g: 40,
    proteinPer100g: 1.1,
    carbsPer100g: 9.3,
    fatsPer100g: 0.1,
  },
  {
    name: "Fokhagyma",
    caloriesPer100g: 149,
    proteinPer100g: 6.4,
    carbsPer100g: 33.1,
    fatsPer100g: 0.5,
  },
  {
    name: "Tojás",
    caloriesPer100g: 155,
    proteinPer100g: 12.6,
    carbsPer100g: 1.1,
    fatsPer100g: 10.6,
  },
  {
    name: "Tej",
    caloriesPer100g: 42,
    proteinPer100g: 3.4,
    carbsPer100g: 4.8,
    fatsPer100g: 1,
  },
  {
    name: "Sajt",
    caloriesPer100g: 402,
    proteinPer100g: 25,
    carbsPer100g: 1.3,
    fatsPer100g: 33,
  },
  {
    name: "Túró",
    caloriesPer100g: 98,
    proteinPer100g: 11,
    carbsPer100g: 3.4,
    fatsPer100g: 4.3,
  },
  {
    name: "Joghurt",
    caloriesPer100g: 59,
    proteinPer100g: 3.5,
    carbsPer100g: 7.7,
    fatsPer100g: 3.3,
  },
  {
    name: "Csirke mell",
    caloriesPer100g: 165,
    proteinPer100g: 31,
    carbsPer100g: 0,
    fatsPer100g: 3.6,
  },
  {
    name: "Pulyka",
    caloriesPer100g: 135,
    proteinPer100g: 29,
    carbsPer100g: 0,
    fatsPer100g: 1.2,
  },
  {
    name: "Marhahús",
    caloriesPer100g: 250,
    proteinPer100g: 26,
    carbsPer100g: 0,
    fatsPer100g: 17,
  },
  {
    name: "Sertéshús",
    caloriesPer100g: 242,
    proteinPer100g: 27,
    carbsPer100g: 0,
    fatsPer100g: 14,
  },
  {
    name: "Hal",
    caloriesPer100g: 206,
    proteinPer100g: 22,
    carbsPer100g: 0,
    fatsPer100g: 12,
  },
  {
    name: "Lazac",
    caloriesPer100g: 208,
    proteinPer100g: 20,
    carbsPer100g: 0,
    fatsPer100g: 13.1,
  },
];

const CREATED_MESSAGE = "Created data!";
const UPDATED_MESSAGE = "Updated data!";
const REMOVED_MESSAGE = "Removed data!";
const DELETED_MESSAGE = "Deleted data!";
const REGISTER_MESSAGE = "Registered successfully!";
const LOGIN_MESSAGE = "Logged in successfully!";
const LOGOUT_MESSAGE = "Logged out successfully!";

module.exports = {
  exercises,
  food,
  CREATED_MESSAGE,
  DELETED_MESSAGE,
  REMOVED_MESSAGE,
  UPDATED_MESSAGE,
  REGISTER_MESSAGE,
  LOGIN_MESSAGE,
  LOGOUT_MESSAGE,
};
